;; brackets imply that all entries should be indented as peers:
(:import [java.io File]
         [org.apache.maven.artifact.ant
          Authentication DependenciesTask RemoteRepository])

;; while parens imply that the first element is special and only the
;; ones after it should be indented as peers:
(:import (java.io File)
         (org.apache.maven.artifact.ant Authentication DependenciesTask
                                        RemoteRepository))

;; Generated by Phil Hagelberg using scpaste at Wed Nov 24 20:58:39 2010. PST. (raw)
